name: Build MonoGame
run-name: Building ${{ github.head_ref }} for ${{ github.actor }} 🚀
on:
    pull_request:
      types: [opened, synchronize, closed]
      branches: [main, Sprint*]
      paths-ignore:
        - '**.md'
jobs:
  Build-Windows:
    name: Build MonoZelda
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.x' # Using .NET SDK 8.0

      - name: Install Mono
        run: sudo apt-get install -y mono-complete

      - name: Install Arial font
        run: |
          sudo apt-get install -y cabextract
          wget https://downloads.sourceforge.net/corefonts/arial32.exe
          cabextract arial32.exe -d /usr/share/fonts/truetype/msttcorefonts
          sudo fc-cache -f -v

      - name: Install Wine
        run: |
          sudo dpkg --add-architecture i386
          sudo mkdir -pm755 /etc/apt/keyrings
          sudo wget -O /etc/apt/keyrings/winehq-archive.key https://dl.winehq.org/wine-builds/winehq.key
          sudo wget -NP /etc/apt/sources.list.d/ https://dl.winehq.org/wine-builds/ubuntu/dists/$(lsb_release -cs)/winehq-$(lsb_release -cs).sources
          sudo apt update
          sudo apt install --install-recommends winehq-stable

      - name: Create 64 bit wine prefix
        run: WINEPREFIX=$HOME/.wine64 WINEARCH=win64 wineboot

      - name: Install d3dcompiler_47 using winetricks
        run: |
          sudo apt-get install -y winetricks
          WINEPREFIX=$HOME/.wine64 winetricks -q d3dcompiler_47

      - name: Install .NET 6
        run: |
          wget https://dotnet.microsoft.com/download/dotnet/thank-you/runtime-6.0.0-linux-x64-binaries
          mkdir -p $HOME/.wine64/dotnet6
          tar zxf dotnet-runtime-6.0.0-linux-x64.tar.gz -C $HOME/.wine64/dotnet6

      - name: Setup MGFXC_WINE_PATH environmental variable
        run: echo "MGFXC_WINE_PATH=$HOME/.wine64" >> $GITHUB_ENV

      - name: Restore dependencies
        run: dotnet restore MonoZelda.sln

      - name: Build the solution
        run: dotnet build MonoZelda.sln --configuration Release

      - name: Publish the project
        run: dotnet publish MonoZelda/MonoZelda.csproj --configuration Release --runtime win-x64 --self-contained true -p:PublishSingleFile=true --output ./Release

      - name: Output Release content
        run: ls -l ./Release

      - uses: actions/upload-artifact@v4
        name: Upload Artifact
        with:
          name: build-${{ github.head_ref }}
          path: ./Release/**
