name: Build MonoGame
run-name: Building ${{ github.head_ref }} for ${{ github.actor }} 🚀
on:
    pull_request:
      types: [opened, synchronize, closed]
      branches: [main, Sprint*]
      paths-ignore:
        - '**.md'
jobs:
  Build-Windows:
    name: Build MonoZelda
    runs-on: ubuntu-latest
    env:
      MGFXC_WINE_PATH: /home/runner/.winemonogame
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.x' # Using .NET SDK 8.0

      - name: Install Mono
        run: sudo apt-get install -y mono-complete

      - name: Install Arial font
        run: |
          sudo apt-get install -y cabextract
          wget https://downloads.sourceforge.net/corefonts/arial32.exe
          cabextract arial32.exe -d /usr/share/fonts/truetype/msttcorefonts
          sudo fc-cache -f -v

      - name: Setup Wine
        run: |
          sudo apt update
          sudo apt install wine64 p7zip-full curl
          wget -qO- https://raw.githubusercontent.com/MonoGame/MonoGame/78636f8056fa981584e3a2a3e0f22e2efbc43ef8/Tools/MonoGame.Effect.Compiler/mgfxc_wine_setup.sh | sh
      
      - name: Restore dependencies
        run: dotnet restore MonoZelda.sln

      - name: Build the solution
        run: dotnet build MonoZelda.sln --configuration Release

      - name: Publish the project
        run: dotnet publish MonoZelda/MonoZelda.csproj --configuration Release --runtime win-x64 --self-contained true -p:PublishSingleFile=true --output ./Release

      - name: Output Release content
        run: ls -l ./Release

      - uses: actions/upload-artifact@v4
        name: Upload Artifact
        with:
          name: build-${{ github.head_ref }}
          path: ./Release/**
