name: Build MonoGame
on:
    pull_request:
      types: [opened, synchronize, closed]
      branches: [main, Sprint*]
      paths-ignore:
        - '**.md'
jobs:
  Build-Windows:
    runs-on: windows-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Build android project
        uses: igotinfected-ci/build-monogame@v2
        with:
          solution-path: '${{ github.workspace }}\LevelBasedGame\LevelBasedGame.sln'
          content-mgcb-path: '${{ github.workspace }}\LevelBasedGame\Content'
          content-mgcb-platform: "Windows"
          csproj-path: '${{ github.workspace }}\LevelBasedGame\LevelBasedGame.csproj'
          build-target: "win-x64"
          build-configuration: "Release"
          
      - uses: actions/upload-artifact@v4
        name: Upload Artifact
        with:
            name: build
            path: bin/Release/**
